In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('data.csv')
df

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
0,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02T11:49:34Z,2017-02-01T18:04:44Z,39.561570,-95.121020,NaN,NaN,2017-02-01T18:04:44Z,NaN,Taco,Gambino's Pizza,KS
1,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02T11:49:34Z,2017-02-01T18:04:44Z,39.561570,-95.121020,NaN,NaN,2016-03-02T11:49:34Z,"Beef, onion, cheddar cheese, lettuce, refried...",Taco,Gambino's Pizza,KS
2,AVwc__dF_7pvs4fz1Ncy,9521 Morton Davis Dr,"Golf Course, American Restaurant, and Resort",Patterson,NaN,2016-10-14T01:58:25Z,2016-10-14T01:58:25Z,37.401855,-121.266703,NaN,NaN,2016-10-14T01:58:25Z,"Beef barbacoa or chicken, spanish rice, pico d...",Smotherd Burrito,Diablo Grande Golf & Country Club,Grayson
3,AVwc__kCByjofQCxkdm-,10550 W I 25 Frontage Rd,Fast Food Restaurant,Longmont,NaN,2016-09-09T17:30:34Z,2016-10-04T05:15:17Z,NaN,NaN,NaN,NaN,2016-09-09T17:30:34Z,NaN,Sausage Burrito,Mcdonald's,Niwot
4,AVwc__WtByjofQCxkdkR,8495 W 3rd St,"Mexican Restaurant Mid-City West,Mexican Resta...",Los Angeles,Mexican,2016-05-19T11:50:25Z,2016-09-11T00:06:37Z,34.080724,-118.389578,NaN,NaN,2016-05-19T11:50:25Z,"Wahoo, avocado, cabbage, pico de gallo and av...",Wahoo Tacogrilled,Baja Fresh Mexican Grill,Bicentennial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77255,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"meat, rice, beans, guacamole, sour cream, chee...",Super Burrito,La Casona Taqueria,California
77256,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"melted cheese, rice, beans & salsa",Steamed Broccoli Burrito,La Casona Taqueria,California
77257,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,meat & salsa,Regular Taco,La Casona Taqueria,California
77258,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"meat, rice, beans & salsa",Regular Burrito,La Casona Taqueria,California
77259,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"stuffed with rice, beans, meat, topped with en...",Azteca Burrito,La Casona Taqueria,California

In [5]:
df['dateAdded'].head(3)

0    2016-03-02T11:49:34Z
1    2016-03-02T11:49:34Z
2    2016-10-14T01:58:25Z
Name: dateAdded, dtype: object

In [6]:
df.dtypes

id                    object
address               object
categories            object
city                  object
cuisines              object
dateAdded             object
dateUpdated           object
latitude             float64
longitude            float64
menus.category        object
menus.currency        object
menus.dateSeen        object
menus.description     object
menus.name            object
name                  object
province              object
dtype: object

In [7]:
df.describe()

           latitude     longitude
count  55636.000000  55636.000000
mean      36.694846    -98.713309
std        4.835124     18.245857
min      -31.986438   -159.492690
25%       33.668355   -117.647150
50%       36.047195    -96.682320
75%       40.588380    -82.679930
max       61.219460    115.903696

In [8]:
df_dropped=df.dropna()
df_dropped

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
72,AVwc_6st_7pvs4fz1Mln,95 Matthews Dr,Restaurant,Hilton Head Island,"Japanese, Thai, Hibachi",2015-10-19T20:43:35Z,2016-08-22T11:22:45Z,32.212044,-80.701132,Appetizers Sushi Bar,USD,2016-08-20T00:00:00Z,"Pepper tuna, pepper white tuna, spicy crab mea...",Taco Tara,Okko Hilton Head,SC
242,AVwc_DjlkufWRAb51GPc,2610 Lyndale Ave S,Restaurant,Minneapolis,"American, Bar / Lounge / Bottle Service",2016-08-01T19:18:23Z,2016-08-22T11:27:55Z,44.954945,-93.288246,Main Course,USD,2016-08-20T00:00:00Z,Main i pico slaw i radish i cilantro-lime crem...,Blackened Fish Tacos,French Meadow Cafe & Bluestem Bar,MN
243,AVwc_DjlkufWRAb51GPc,2610 Lyndale Ave S,Restaurant,Minneapolis,"American, Bar / Lounge / Bottle Service",2016-08-01T19:18:23Z,2016-08-22T11:27:55Z,44.954945,-93.288246,Main Course,USD,2016-08-20T00:00:00Z,Blackened organic tempeh i tempeh chorizo i pi...,Blackened Tempeh Tacos,French Meadow Cafe & Bluestem Bar,MN
259,AVwc_DW1_7pvs4fz1DBV,119 W Clay St,"Bistro,American Restaurant,New American Restau...",Mebane,"American Restaurants,American, Contemporary Am...",2016-03-31T02:34:19Z,2017-07-03T17:12:10Z,36.097057,-79.267750,Main,USD,2016-04-24T00:00:00Z,"Grilled or blackened with house made tortilla,...",Shrimp or Mahi Taco,Mebane Downtown Table,NC
261,AVwc_DW1_7pvs4fz1DBV,119 W Clay St,"Bistro,American Restaurant,New American Restau...",Mebane,"American Restaurants,American, Contemporary Am...",2016-03-31T02:34:19Z,2017-07-03T17:12:10Z,36.097057,-79.267750,Starters,USD,2016-04-24T00:00:00Z,"Slow cooked leg of duck, house made tortilla w...",Duck Confit Tacos,Mebane Downtown Table,NC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76997,AVz0WZ18FcQ3k02bDO8m,29 Crown Rd.Building B,Restaurant,Weatherford,Mexican,2017-06-29T14:55:32Z,2017-06-29T14:55:32Z,32.752010,-97.669332,Main,USD,2017-06-28T17:41:09.905Z,"A new favorite Slowsmoked brisket, served in y...",Brisket Tacos,Los Vaqueros - West,TX
76998,AVz0WZ18FcQ3k02bDO8m,29 Crown Rd.Building B,Restaurant,Weatherford,Mexican,2017-06-29T14:55:32Z,2017-06-29T14:55:32Z,32.752010,-97.669332,Main,USD,2017-06-28T17:41:09.905Z,The chefs favorite when he is too busy to sit ...,Johnnys Burrito Bowl,Los Vaqueros - West,TX
76999,AVz0WZ18FcQ3k02bDO8m,29 Crown Rd.Building B,Restaurant,Weatherford,Mexican,2017-06-29T14:55:32Z,2017-06-29T14:55:32Z,32.752010,-97.669332,Main,USD,2017-06-28T17:41:09.905Z,"With chili con queso, Spanish rice and refried...",One Beef or Chicken Burrito,Los Vaqueros - West,TX
77000,AVz0WZf3-gnIPe8DUW4y,2300 Matlock Rd. Suite 21,Restaurant,Mansfield,"Mexican, American, Seafood",2017-06-29T14:55:31Z,2017-06-29T14:55:31Z,32.594093,-97.106282,Ensaladas Salads,USD,2017-06-28T17:33:26.597Z,Seasoned picadillo beef served with fresh mixe...,Ensalada Taco,El Primo's Mexican Grill & Cantina,TX
77014,AVz0WZsS-gnIPe8DUW45,4150 North MacArthur Blvd,Restaurant,Irving,"Steakhouse, American",2017-06-29T14:55:32Z,2017-06-29T14:55:32Z,32.862452,-96.959246,Air,USD,2017-06-28T17:36:57.862Z,peppers onions jack cheese flour tortilla sour...,Beer Can Chicken Tacos,LAW at Four Seasons Dallas,TX

In [9]:
df.iloc[404]

id                                         AVwc_kwakufWRAb51L0H
address                                           4 N Walnut St
categories           Restaurant,Pizza Place,American Restaurant
city                                                     Dexter
cuisines                                                Italian
dateAdded                                  2016-04-05T02:01:43Z
dateUpdated                                2016-05-16T23:17:01Z
latitude                                               36.79324
longitude                                             -89.95773
menus.category                                              NaN
menus.currency                                              NaN
menus.dateSeen        2016-05-16T23:17:01Z,2016-04-05T02:01:43Z
menus.description                                           NaN
menus.name                                                 Taco
name                                       Dexter Pizza Company
province                                                     MO
Name: 404, dtype: object

In [10]:
array = df[(df['city'] == 'California') & (df['province'] == 'MO')].index.tolist()
array

[40483,
 52930,
 52931,
 52932,
 52933,
 52934,
 52935,
 52936,
 52937,
 52938,
 52939,
 65070]

In [11]:
array = df[(df['city'] == 'California') & (df['name'] == 'Taco Bell')].index.tolist()
array

[52930, 52931, 52932, 52933, 52934, 52935, 52936, 52937, 52938, 52939]

In [12]:
data = df

In [13]:
result = data[((data['name'] == 'Taco Bell') | (data['city'] == 'New York')) & (~(data['menus.name'].isin(['Volcano Taco', 'Fresco Soft Taco'])))]
result

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
131,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Volcano Burrito,Taco Bell,NH
132,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Taco 12 Pack,Taco Bell,NH
133,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Grilled Steak Soft Taco,Taco Bell,NH
135,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Fresco Grilled Steak Soft Taco,Taco Bell,NH
136,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Fresco Crunchy Taco,Taco Bell,NH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76904,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Tacos,USD,2016-08-21T00:00:00Z,NaN,Trio of Tacos,Hell's Kitchen,Nyc
76905,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,"Huevos, Etc.",USD,2016-08-07T00:00:00Z,NaN,Brunch Burrito,Hell's Kitchen,Nyc
76906,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Botanas,USD,2016-08-07T00:00:00Z,NaN,Grilled Chicken Mini Burrito,Hell's Kitchen,Nyc
76907,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Botanas,USD,2016-08-07T00:00:00Z,with pumpkin seed guacamole,Grilled Vegetable Mini Burrito,Hell's Kitchen,Nyc
76908,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Main,NaN,2016-08-21T00:00:00Z,NaN,Burritos,Hell's Kitchen,Nyc

In [14]:
result = data[~data['menus.currency'].isna()]
result

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
15,AVwc_1y6kufWRAb51O6w,906 Park Ave SW,"Coffee Shop,Restaurants,Coffeehouses",Albuquerque,Coffee Shops,2016-06-05T20:15:56Z,2017-07-06T13:28:29Z,35.085320,-106.657616,NaN,USD,"2016-06-05T20:15:56Z,2016-10-20T07:09:38Z","Potatoes, onion, peppers, mushroom, avocado, b...",Mondo Veggie Burrito,Java Joe's,NM
16,AVwc_1y6kufWRAb51O6w,906 Park Ave SW,"Coffee Shop,Restaurants,Coffeehouses",Albuquerque,Coffee Shops,2016-06-05T20:15:56Z,2017-07-06T13:28:29Z,35.085320,-106.657616,NaN,USD,"2016-06-05T20:15:56Z,2016-10-20T07:09:38Z","Grilled tofu, potatoes and your choice of chil...",Tofu Burrito,Java Joe's,NM
17,AVwc_1y6kufWRAb51O6w,906 Park Ave SW,"Coffee Shop,Restaurants,Coffeehouses",Albuquerque,Coffee Shops,2016-06-05T20:15:56Z,2017-07-06T13:28:29Z,35.085320,-106.657616,NaN,USD,"2016-06-05T20:15:56Z,2016-10-20T07:09:38Z",NaN,Black Bean Burrito,Java Joe's,NM
18,AVwc_2OQ_7pvs4fz1L5H,100 W Higgins Rd,Restaurant,Barrington,"Mexican, Latin American",2016-07-26T17:39:41Z,2016-08-26T05:25:56Z,42.074974,-88.189151,NaN,USD,2016-08-22T00:00:00Z,NaN,Burrito De Rajas,Mago Grill & Cantina - South Barrington,Fox Rv Vly Gn
19,AVwc_2OQ_7pvs4fz1L5H,100 W Higgins Rd,Restaurant,Barrington,"Mexican, Latin American",2016-07-26T17:39:41Z,2016-08-26T05:25:56Z,42.074974,-88.189151,NaN,USD,2016-08-22T00:00:00Z,"lettuce, chihuahua cheese, black beans, mexica...",Taco,Mago Grill & Cantina - South Barrington,Fox Rv Vly Gn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77255,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"meat, rice, beans, guacamole, sour cream, chee...",Super Burrito,La Casona Taqueria,California
77256,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"melted cheese, rice, beans & salsa",Steamed Broccoli Burrito,La Casona Taqueria,California
77257,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,meat & salsa,Regular Taco,La Casona Taqueria,California
77258,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"meat, rice, beans & salsa",Regular Burrito,La Casona Taqueria,California
77259,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"stuffed with rice, beans, meat, topped with en...",Azteca Burrito,La Casona Taqueria,California

In [15]:
data.groupby('menus.currency').nunique(dropna=False)

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.dateSeen,menus.description,menus.name,name,province
menus.currency,,,,,,,,,,,,,,,
EUR,1,1,1,1,1,1,1,1,1,1,16,16,16,1,1
USD,10464,9936,5424,2360,1316,9966,9891,7572,7574,817,9402,12904,13209,8788,656

In [16]:
data['categories']

0        Restaurant Delivery Service,Restaurants,Pizza,...
1        Restaurant Delivery Service,Restaurants,Pizza,...
2             Golf Course, American Restaurant, and Resort
3                                     Fast Food Restaurant
4        Mexican Restaurant Mid-City West,Mexican Resta...
                               ...
77255                                           Restaurant
77256                                           Restaurant
77257                                           Restaurant
77258                                           Restaurant
77259                                           Restaurant
Name: categories, Length: 77260, dtype: object

In [17]:
data[['categories']]

                                              categories
0      Restaurant Delivery Service,Restaurants,Pizza,...
1      Restaurant Delivery Service,Restaurants,Pizza,...
2           Golf Course, American Restaurant, and Resort
3                                   Fast Food Restaurant
4      Mexican Restaurant Mid-City West,Mexican Resta...
...                                                  ...
77255                                         Restaurant
77256                                         Restaurant
77257                                         Restaurant
77258                                         Restaurant
77259                                         Restaurant

[77260 rows x 1 columns]

In [18]:
df[['categories', 'city']]

                                              categories           city
0      Restaurant Delivery Service,Restaurants,Pizza,...       Atchison
1      Restaurant Delivery Service,Restaurants,Pizza,...       Atchison
2           Golf Course, American Restaurant, and Resort      Patterson
3                                   Fast Food Restaurant       Longmont
4      Mexican Restaurant Mid-City West,Mexican Resta...    Los Angeles
...                                                  ...            ...
77255                                         Restaurant  San Francisco
77256                                         Restaurant  San Francisco
77257                                         Restaurant  San Francisco
77258                                         Restaurant  San Francisco
77259                                         Restaurant  San Francisco

[77260 rows x 2 columns]

In [27]:
df['city'].value_counts()

San Diego            1924
Los Angeles          1603
Chicago              1186
San Francisco        1120
New York             1085
                     ...
Corfu                   1
Sharon Hill             1
Lawrence Township       1
Selinsgrove             1
Santa Clarita           1
Name: city, Length: 3601, dtype: int64

In [40]:
data = df

result = data[data['name'] == 'Taco Bell']['city'].value_counts()[:5]
result

Indianapolis        84
Columbus            63
Charleston          63
Tampa               62
South Lake Tahoe    42
Name: city, dtype: int64

In [49]:
data = df
data['dateAdded'] = pd.to_datetime(data['dateAdded'])
data[data['dateAdded'].dt.month == 10]

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
2,AVwc__dF_7pvs4fz1Ncy,9521 Morton Davis Dr,"Golf Course, American Restaurant, and Resort",Patterson,NaN,2016-10-14 01:58:25+00:00,2016-10-14T01:58:25Z,37.401855,-121.266703,NaN,NaN,2016-10-14T01:58:25Z,"Beef barbacoa or chicken, spanish rice, pico d...",Smotherd Burrito,Diablo Grande Golf & Country Club,Grayson
21,AVwc_3Kp_7pvs4fz1MDQ,116 Pleasant St,"Restaurant,Seafood Restaurants,Take Out Restau...",Easthampton,"American,Seafood Restaurants",2015-10-26 23:10:06+00:00,2016-09-19T17:41:29Z,42.273525,-72.663124,NaN,USD,2016-09-19T17:41:29Z,"Crispy house-smoked pork belly, hoisin sauce, ...",Korean Pork Belly Tacos,Riff's Joint,Westhampton
22,AVwc_3Kp_7pvs4fz1MDQ,116 Pleasant St,"Restaurant,Seafood Restaurants,Take Out Restau...",Easthampton,"American,Seafood Restaurants",2015-10-26 23:10:06+00:00,2016-09-19T17:41:29Z,42.273525,-72.663124,NaN,USD,2016-09-19T17:41:29Z,"Black beans, corn and black bean salsa, guacam...",Speedy Gonzalez Burrito,Riff's Joint,Westhampton
23,AVwc_3Kp_7pvs4fz1MDQ,116 Pleasant St,"Restaurant,Seafood Restaurants,Take Out Restau...",Easthampton,"American,Seafood Restaurants",2015-10-26 23:10:06+00:00,2016-09-19T17:41:29Z,42.273525,-72.663124,NaN,USD,2016-09-19T17:41:29Z,"Black beans, jasmine rice and peanut slaw",Thai Dyed Burrito,Riff's Joint,Westhampton
24,AVwc_3Kp_7pvs4fz1MDQ,116 Pleasant St,"Restaurant,Seafood Restaurants,Take Out Restau...",Easthampton,"American,Seafood Restaurants",2015-10-26 23:10:06+00:00,2016-09-19T17:41:29Z,42.273525,-72.663124,NaN,USD,2016-09-19T17:41:29Z,"Black beans, cheddar, salsa, rice, sour cream,...",Burrito Supreme,Riff's Joint,Westhampton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76927,AVweZtCQByjofQCxx3uK,11688 Us 23,Fast Food Restaurant,Waverly,NaN,2015-10-22 19:23:28+00:00,2016-08-09T10:11:49Z,39.119935,-82.993279,NaN,NaN,2015-10-22T19:23:28Z,NaN,Sausage Burrito,Mcdonalds,OH
76946,AVweZZ31IN2L1WUf4jVT,2521 Bagby,Restaurant,Houston,"Continental, Contemporary European, Global, In...",2015-10-19 20:42:46+00:00,2016-08-22T11:26:45Z,29.748747,-95.379022,Specialty Bar Menu,USD,2016-04-24T00:00:00Z,NaN,Ahi Tuna Crispy Taco (2),Charivari,TX
76947,AVweZZ31IN2L1WUf4jVT,2521 Bagby,Restaurant,Houston,"Continental, Contemporary European, Global, In...",2015-10-19 20:42:46+00:00,2016-08-22T11:26:45Z,29.748747,-95.379022,Specialty Bar Menu,USD,2016-08-20T00:00:00Z,NaN,Pork Shank (schweinehaxe) Taco (2),Charivari,TX
76948,AVweZ-ZKIN2L1WUf4n9V,110 W Hubbard,Restaurant,Chicago,"Contemporary European, Bar / Lounge / Bottle S...",2015-10-19 20:37:03+00:00,2016-08-09T02:40:48Z,41.890262,-87.631646,Beginners,USD,2016-08-07T00:00:00Z,"Corn tortilla, avocado, sesame, soy sauce, mar...",Tuna Tartare Tacos,Hubbard Inn,IL
76949,AVweZ-ZKIN2L1WUf4n9V,110 W Hubbard,Restaurant,Chicago,"Contemporary European, Bar / Lounge / Bottle S...",2015-10-19 20:37:03+00:00,2016-08-09T02:40:48Z,41.890262,-87.631646,Lunch Plates,USD,2016-04-24T00:00:00Z,NaN,Tuna Tartare Taco,Hubbard Inn,IL

In [53]:
data = df
data[data['categories'].str.contains('Pizza')]

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
0,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02 11:49:34+00:00,2017-02-01T18:04:44Z,39.561570,-95.12102,NaN,NaN,2017-02-01T18:04:44Z,NaN,Taco,Gambino's Pizza,KS
1,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02 11:49:34+00:00,2017-02-01T18:04:44Z,39.561570,-95.12102,NaN,NaN,2016-03-02T11:49:34Z,"Beef, onion, cheddar cheese, lettuce, refried...",Taco,Gambino's Pizza,KS
66,AVwc_59U_7pvs4fz1Md3,3250 Kennedy Cir,"Pizza,Take Out Restaurants,Caterers,Restaurant...",Dubuque,Pizza,2016-03-29 04:45:06+00:00,2016-05-05T12:40:51Z,42.505264,-90.72141,NaN,NaN,"2016-05-05T12:40:51Z,2016-03-29T04:45:06Z",NaN,Taco Supreme,Falbo Bros Pizzeria,IA
67,AVwc_59U_7pvs4fz1Md3,3250 Kennedy Cir,"Pizza,Take Out Restaurants,Caterers,Restaurant...",Dubuque,Pizza,2016-03-29 04:45:06+00:00,2016-05-05T12:40:51Z,42.505264,-90.72141,NaN,NaN,"2016-05-05T12:40:51Z,2016-03-29T04:45:06Z",NaN,Taco,Falbo Bros Pizzeria,IA
158,AVwc_AmZkufWRAb51FxA,133 Howard St,"Pizza,Restaurants",Braintree,Pizza,2016-09-19 17:43:53+00:00,2016-09-19T17:43:53Z,42.233826,-70.98024,NaN,USD,2016-09-19T17:43:53Z,"Large salsa, pizza cheese, hamburger, hot pepp...",Mexican Taco,New England House of Pizza,Braintree Hld
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76256,AVweVOBFByjofQCxxRnN,3000 N Dinuba Blvd,"Latin American Restaurants,Take Out Restaurant...",Visalia,"Latin American Restaurants,Mexican",2016-07-06 20:48:02+00:00,2016-11-18T15:46:04Z,36.351383,-119.29696,NaN,USD,2016-07-06T20:48:02Z,"Roasted pork, cabbage, cilantro, onion, beans,...",Tacos De Adobado,Figaro's Mexican Grill,CA
76291,AVweVXD4ByjofQCxxS7L,35 N Farview Ave,"Italian Restaurant,Pizza Place",Paramus,NaN,2016-03-15 19:34:54+00:00,2016-05-06T20:35:40Z,NaN,NaN,NaN,USD,2016-03-15T19:34:54Z,NaN,Taco,La Bella Roma Pizzeria,NJ
76507,AVweWyOEkufWRAb5CNJU,1516 E Historic Highway 66,"Take Out Restaurants,Restaurants,Italian Resta...",Gallup,Take Out Restaurants,2017-01-12 18:46:56+00:00,2017-01-12T18:46:56Z,35.530148,-108.71973,NaN,NaN,2017-01-12T18:46:56Z,"Beef, Whole Beans, Cheddar Cheese, Onion, Lett...",Navajo Taco,Big Cheese Pizza,Pinedale
76669,AVweXxalByjofQCxxnWC,1895 Washington Blvd,"Bars,Restaurants,Bar & Grills,Pizza",Ogden,Bars,2016-12-25 18:11:56+00:00,2016-12-25T18:11:56Z,41.233300,-111.97047,NaN,USD,2016-12-25T18:11:56Z,"Our famous chili verde, string potatoes, three...",Chili Verde Breakfast Burrito,Slackwater Pub Pizzeria,Marriott-slaterville City
76709,AVweYFH-ByjofQCxxqHG,620 Water St S,"Bars,Pizza,Italian Restaurants,Family Style Re...",Northfield,Bars,2016-04-03 12:15:30+00:00,2016-04-03T12:15:30Z,44.453735,-93.16171,NaN,NaN,2016-04-03T12:15:30Z,"Mild Tomato chili sauce, chipotle beef topped ...",Taco - A South of The Boarder Favorite,Carbone's Pizzeria,MN

In [62]:
data = df
data['dateAdded'] = pd.to_datetime(data['dateAdded'], errors='coerce')
data['dateUpdated'] = pd.to_datetime(data['dateUpdated'], errors='coerce')
data['update_delta'] = (data['dateUpdated'] - data['dateAdded']).dt.days
data['update_delta'].mean()

326.22456639917164

In [63]:
data['update_delta'].median()

364.0

In [85]:
data = df

data = data[data['categories'].str.split(',').str.len() > 20].groupby('province')[['longitude']].min()
data = data.apply(round, ndigits=3)
data.to_csv('task19.csv', sep=';')
data

              longitude
province
AZ             -110.136
CA             -122.417
DC              -77.075
G P O           -73.990
KY              -87.455
MA              -71.055
MD              -77.453
NY              -76.794
St Simons Is    -81.394
TX              -94.939
VA              -77.093
WA             -122.383
WI              -89.377