In [1]:
import pandas as pd

In [2]:
playstore = pd.read_csv('playstore.csv')
playstore

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10835,10835,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10836,10836,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10837,10837,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10838,10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10839,10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [3]:
data_head = playstore.head(3)
data_tail = playstore.tail(3)

In [4]:
data_head

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up

In [5]:
data_tail

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10837,10837,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10838,10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10839,10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [6]:
n_col = playstore.shape[1]
n_row = playstore.shape[0]

n_col, n_row

(14, 10840)

In [7]:
unique_apps = playstore['App'].nunique()
unique_apps

9659

In [8]:
rating_missing = playstore['Rating'].isna().sum()
rating_missing

1474

In [9]:
df1 = playstore.iloc[0:3]
df2 = playstore.iloc[5:8]
df3 = playstore.iloc[15:19]

df = pd.concat([df1, df2, df3])[['App', 'Size', 'Genres', 'Current Ver']]

df.to_csv('task6.csv', index=True)
df

,App,Size,Genres,Current Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,19M,Art & Design,1.0.0
1,Coloring book moana,14M,Art & Design;Pretend Play,2.0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",8.7M,Art & Design,1.2.4
5,Paper flowers instructions,5.6M,Art & Design,1.0
6,Smoke Effect Photo Maker - Smoke Editor,19M,Art & Design,1.1
7,Infinite Painter,29M,Art & Design,6.1.61.1
15,Learn To Draw Kawaii Characters,2.7M,Art & Design,NaN
16,Photo Designer - Write your name with shapes,5.5M,Art & Design,3.1
17,350 Diy Room Decor Ideas,17M,Art & Design,1.0
18,FlipaClip - Cartoon animation,39M,Art & Design,2.2.5

In [10]:
unique_playstore = playstore.drop_duplicates('App').reset_index(drop=True)
unique_playstore

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9654,10835,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
9655,10836,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
9656,10837,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
9657,10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
9658,10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [11]:
mapping = dict(zip(playstore.columns, playstore.columns.str.lower().str.replace(' ', '_')))
playstore = playstore.rename(columns=mapping)
playstore

,unnamed:_0,app,category,rating,reviews,size,installs,type,price,content_rating,genres,last_updated,current_ver,android_ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10835,10835,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10836,10836,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10837,10837,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10838,10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10839,10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [12]:
unique_playstore['Type'].value_counts(normalize=True).round(2)

Free    0.92
Paid    0.08
Name: Type, dtype: float64

In [13]:
#playstore['Reviews'] = playstore['Reviews'].astype(int)
education_playstore = playstore[(playstore['category'] == 'EDUCATION') & (playstore['reviews'] >= 1000)].reset_index(drop=True)
education_playstore

,unnamed:_0,app,category,rating,reviews,size,installs,type,price,content_rating,genres,last_updated,current_ver,android_ver
0,699,Duolingo: Learn Languages Free,EDUCATION,4.7,6289924,Varies with device,"100,000,000+",Free,0,Everyone,Education;Education,"August 1, 2018",Varies with device,Varies with device
1,700,TED,EDUCATION,4.6,181893,18M,"10,000,000+",Free,0,Everyone 10+,Education,"July 27, 2018",3.2.5,4.1 and up
2,701,English Communication - Learn English for Chin...,EDUCATION,4.7,2544,18M,"100,000+",Free,0,Everyone,Education,"December 29, 2017",3.1,4.0 and up
3,702,Khan Academy,EDUCATION,4.6,85375,21M,"5,000,000+",Free,0,Everyone,Education,"July 27, 2018",5.0.0,4.1 and up
4,703,Learn English with Wlingua,EDUCATION,4.7,314299,3.3M,"10,000,000+",Free,0,Everyone,Education,"May 2, 2018",1.94.9,4.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,848,SoloLearn: Learn to Code for Free,EDUCATION,4.8,256079,7.6M,"1,000,000+",Free,0,Teen,Education,"July 12, 2018",2.2.4,4.0.3 and up
131,849,Kids Learn Languages by Mondly,EDUCATION,4.4,2078,Varies with device,"100,000+",Free,0,Everyone,Education;Education,"December 24, 2017",1.0.2,4.1 and up
132,850,Blinkist - Nonfiction Books,EDUCATION,4.1,16103,13M,"1,000,000+",Free,0,Everyone,Education,"July 31, 2018",5.7.1,4.1 and up
133,853,Toca Life: City,EDUCATION,4.7,31085,24M,"500,000+",Paid,$3.99,Everyone,Education;Pretend Play,"July 6, 2018",1.5-play,4.4 and up
134,854,Toca Life: Hospital,EDUCATION,4.7,3528,24M,"100,000+",Paid,$3.99,Everyone,Education;Pretend Play,"June 12, 2018",1.1.1-play,4.4 and up

In [14]:
playstore['price'] = playstore['price'].str.replace('$', '').astype(float)

C:\Users\Гарден Вейп\AppData\Local\Temp\ipykernel_12680\3197742707.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  playstore['price'] = playstore['price'].str.replace('$', '').astype(float)

In [15]:
mapping = dict(zip(unique_playstore.columns, unique_playstore.columns.str.lower().str.replace(' ', '_')))
unique_playstore = unique_playstore.rename(columns=mapping)
unique_playstore['price'] = unique_playstore['price'].str.replace('$', '').astype(float)

unique_playstore.pivot_table(
    values = ['price', 'rating', 'reviews'],
    index = ['category', 'type'],
    aggfunc = 'mean',
)

C:\Users\Гарден Вейп\AppData\Local\Temp\ipykernel_12680\1945835005.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  unique_playstore['price'] = unique_playstore['price'].str.replace('$', '').astype(float)

                         price    rating        reviews
category          type
ART_AND_DESIGN    Free  0.0000  4.337931   23230.114754
                  Paid  1.9900  4.733333     722.000000
AUTO_AND_VEHICLES Free  0.0000  4.184722   14140.280488
                  Paid  4.4900  4.600000    1387.666667
BEAUTY            Free  0.0000  4.278571    7476.226415
...                        ...       ...            ...
TRAVEL_AND_LOCAL  Paid  4.1625  4.100000    1506.083333
VIDEO_PLAYERS     Free  0.0000  4.043056  424347.176101
                  Paid  2.6150  4.100000    3341.750000
WEATHER           Free  0.0000  4.229231  171249.619718
                  Paid  4.0525  4.371429   17055.125000

[63 rows x 3 columns]

In [16]:

unique_playstore.groupby(['category', 'type']).agg(
    mean_price=('price', 'mean'),
    mean_rating=('rating', 'mean'),
    mean_reviews=('reviews', 'mean')
).round(2).to_csv('pivot.csv')
unique_playstore.groupby(['category', 'type']).agg(
    mean_price=('price', 'mean'),
    mean_rating=('rating', 'mean'),
    mean_reviews=('reviews', 'mean')).round(2)

                        mean_price  mean_rating  mean_reviews
category          type
ART_AND_DESIGN    Free        0.00         4.34      23230.11
                  Paid        1.99         4.73        722.00
AUTO_AND_VEHICLES Free        0.00         4.18      14140.28
                  Paid        4.49         4.60       1387.67
BEAUTY            Free        0.00         4.28       7476.23
...                            ...          ...           ...
TRAVEL_AND_LOCAL  Paid        4.16         4.10       1506.08
VIDEO_PLAYERS     Free        0.00         4.04     424347.18
                  Paid        2.62         4.10       3341.75
WEATHER           Free        0.00         4.23     171249.62
                  Paid        4.05         4.37      17055.12

[63 rows x 3 columns]

In [17]:
res = unique_playstore.pivot_table(
    values=['price', 'rating', 'reviews'],
    index=['category', 'type'],
    aggfunc='mean'
).set_axis(['mean_price', 'mean_rating', 'mean_reviews'], axis=1)

res

                        mean_price  mean_rating   mean_reviews
category          type
ART_AND_DESIGN    Free      0.0000     4.337931   23230.114754
                  Paid      1.9900     4.733333     722.000000
AUTO_AND_VEHICLES Free      0.0000     4.184722   14140.280488
                  Paid      4.4900     4.600000    1387.666667
BEAUTY            Free      0.0000     4.278571    7476.226415
...                            ...          ...            ...
TRAVEL_AND_LOCAL  Paid      4.1625     4.100000    1506.083333
VIDEO_PLAYERS     Free      0.0000     4.043056  424347.176101
                  Paid      2.6150     4.100000    3341.750000
WEATHER           Free      0.0000     4.229231  171249.619718
                  Paid      4.0525     4.371429   17055.125000

[63 rows x 3 columns]

In [18]:
res = unique_playstore.pivot_table(
    values=['price', 'rating', 'reviews'],
    index=['category', 'type'],
    aggfunc='mean'
).add_prefix('mean_').round({
    'mean_price': 2,    # Цену округляем до копеек (2 знака)
    'mean_rating': 1,   # Рейтинг округляем до десятых (1 знак)
    'mean_reviews': 2   # Количество отзывов делаем целым числом (0 знаков)
}).to_csv('pivot.csv')

res